In [1]:
import pandas as pd

In [2]:
zzin_df = pd.DataFrame({'P_score': [], 'predict' : [],'real':[], 'stock_name' : [], 'stock_code': [], 'Date' : [], 'Nasdaq' : []})

In [7]:
for i in range(1,11) :
    temp_df = pd.read_csv("C:/Users/admin/Desktop/Project_git/resources/new_labelling_test/new_labelling_test{}.csv".format(i), parse_dates=['Date'], index_col=[0], dtype = {"stock_code" :str}, encoding = "euc-kr")
    zzin_df = zzin_df.append(temp_df)
zzin_df

    P_score predict real stock_name stock_code       Date  Nasdaq
0    100.00      P0   P0       가온전선     000500 2020-10-23     NaN
0     81.75      P0   K0      동양이엔피     079960 2020-10-23     NaN
0     81.20      P0   K0   피에스케이홀딩스     031980 2020-10-23     NaN
0     80.70      P0   M0    서플러스글로벌     140070 2020-10-23     NaN
0     79.63      P0   M0       디아이씨     092200 2020-10-23     NaN
..      ...     ...  ...        ...        ...        ...     ...
0     83.54      P0   P0         화신     010690 2020-06-01     NaN
0     81.05      P0   K0     LG생활건강     051900 2020-06-01     NaN
0     80.32      P0   P0      성도이엔지     037350 2020-06-01     NaN
0     78.91      P0   P0       알에프텍     061040 2020-06-01     NaN
0     78.67      P0   P0     스카이라이프     053210 2020-06-01     NaN

[500 rows x 7 columns]

In [9]:
zzin_df.to_csv("C:/Users/admin/Desktop/Project_git/resources/new_labelling_test/nl_zzin.csv")